### ISSUE TITLE
Suggestions: please add example of how to add more ALLOWED_HOSTS in sample.env

### ISSUE THREAD

**Issue by NoMoneyDev** [OmegaOoh/ku-polls#51]
Current sample.env
```
SECRET_KEY = 'django-insecure'
DEBUG = False
ALLOWED_HOSTS = 'localhost'
TIME_ZONE = 'Asia/Bangkok'
```

Suggested sample.env
```
SECRET_KEY = 'secret-key-here'
DEBUG = False
ALLOWED_HOSTS = 'localhost, add-new-hosts-here'
TIME_ZONE = 'Asia/Bangkok'
```

**Comment by OmegaOoh** [comment]
![Installation.md ALLOWED_HOSTS instruction](https://github.com/user-attachments/assets/9da2cf14-88f8-45bf-89a0-f512fe2f9d28)

I've added the information about how to configure the ALLOWED_HOSTS values in installation.md Instead of adding it to sample.env. Which will be merged into the master branch in #53.
